<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class UserUpdateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name' => 'required|max:30',
            'about' => 'nullable|max:500',
            'avatar' => 'nullable',
            'old_pass' => 'nullable|min:8|max:30',
            'new_pass' => 'nullable|min:8|max:30',
            'twitter' => 'nullable',
            'github'  => 'nullable',
            'facebook' => 'nullable',
            'linkedin' => 'nullable',
            'instagram' => 'nullable'
        ];
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
